package com.clr.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseErrorPage<M extends BaseErrorPage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setTagId(java.lang.Integer tagId) {
		set("tag_id", tagId);
	}

	public java.lang.Integer getTagId() {
		return get("tag_id");
	}

	public void setCurrentPage(java.lang.Integer currentPage) {
		set("currentPage", currentPage);
	}

	public java.lang.Integer getCurrentPage() {
		return get("currentPage");
	}

}
