package com.clr.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTag<M extends BaseTag<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setTagL1(java.lang.String tagL1) {
		set("tag_l1", tagL1);
	}

	public java.lang.String getTagL1() {
		return get("tag_l1");
	}

	public void setTagL2(java.lang.String tagL2) {
		set("tag_l2", tagL2);
	}

	public java.lang.String getTagL2() {
		return get("tag_l2");
	}

	public void setPages(java.lang.Integer pages) {
		set("pages", pages);
	}

	public java.lang.Integer getPages() {
		return get("pages");
	}

	public void setFinalPage(java.lang.Integer finalPage) {
		set("final_page", finalPage);
	}

	public java.lang.Integer getFinalPage() {
		return get("final_page");
	}

}
