package com.clr.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTagId(java.lang.Integer tagId) {
		set("tag_id", tagId);
	}

	public java.lang.Integer getTagId() {
		return get("tag_id");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setAuthors(java.lang.String authors) {
		set("authors", authors);
	}

	public java.lang.String getAuthors() {
		return get("authors");
	}

	public void setAuthorIds(java.lang.String authorIds) {
		set("author_ids", authorIds);
	}

	public java.lang.String getAuthorIds() {
		return get("author_ids");
	}

	public void setTranslator(java.lang.String translator) {
		set("translator", translator);
	}

	public java.lang.String getTranslator() {
		return get("translator");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}

	public java.lang.String getImage() {
		return get("image");
	}

	public void setSummary(java.lang.String summary) {
		set("summary", summary);
	}

	public java.lang.String getSummary() {
		return get("summary");
	}

	public void setCatalog(java.lang.String catalog) {
		set("catalog", catalog);
	}

	public java.lang.String getCatalog() {
		return get("catalog");
	}

	public void setPages(java.lang.Integer pages) {
		set("pages", pages);
	}

	public java.lang.Integer getPages() {
		return get("pages");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setPubdate(java.util.Date pubdate) {
		set("pubdate", pubdate);
	}

	public java.util.Date getPubdate() {
		return get("pubdate");
	}

	public void setPublisher(java.lang.String publisher) {
		set("publisher", publisher);
	}

	public java.lang.String getPublisher() {
		return get("publisher");
	}

	public void setIsbn10(java.lang.String isbn10) {
		set("isbn10", isbn10);
	}

	public java.lang.String getIsbn10() {
		return get("isbn10");
	}

	public void setIsbn13(java.lang.String isbn13) {
		set("isbn13", isbn13);
	}

	public java.lang.String getIsbn13() {
		return get("isbn13");
	}

	public void setRating(java.lang.Integer rating) {
		set("rating", rating);
	}

	public java.lang.Integer getRating() {
		return get("rating");
	}

	public void setNumRaters(java.lang.Double numRaters) {
		set("numRaters", numRaters);
	}

	public java.lang.Double getNumRaters() {
		return get("numRaters");
	}

}
