package com.clr.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEpisodes<M extends BaseEpisodes<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTag(java.lang.String tag) {
		set("tag", tag);
	}

	public java.lang.String getTag() {
		return get("tag");
	}

}
