package com.clr.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("author", "id", Author.class);
		arp.addMapping("book", "id", Book.class);
		arp.addMapping("episodes", "id", Episodes.class);
		arp.addMapping("error_page", "id", ErrorPage.class);
		arp.addMapping("movie", "id", Movie.class);
		arp.addMapping("tag", "id", Tag.class);
	}
}

