package com.clr.model;

import com.clr.model.BaseAuthor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Author extends BaseAuthor<Author> {
	public static final Author dao = new Author();
}
