package com.clr.model;

import com.clr.model.BaseBook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Book extends BaseBook<Book> {
	public static final Book dao = new Book();
}
