package com.clr.model;

import com.clr.model.BaseEpisodes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Episodes extends BaseEpisodes<Episodes> {
	public static final Episodes dao = new Episodes();
}
