package com.clr.model;

import com.clr.model.BaseErrorPage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ErrorPage extends BaseErrorPage<ErrorPage> {
	public static final ErrorPage dao = new ErrorPage();
}
